### ISSUE TITLE
Fix paths and syntax

### ISSUE THREAD

**Issue by nixkitax** [micahtdew/circom-test#1]
here we go, the code is fixed: 

```pragma circom  2.0.0;
include "./circomlib/circuits/sha256/sha256.circom";

template hashing() {
    signal input in[1];
    signal output out[256];
    
    component SHA = Sha256(1);
    SHA.in <== in;
    out <== SHA.out;
}

component main = hashing();
```
1. you have to declare input (1 as you put at the start and 256 because it is the result of the hash function) and output;
2. component SHA does not have an array as input of function, it has num of bits
3. terminal command is:
```
circom circuits/hash.circom -l node_modules
```
contact me on tg if you have more issues :D

**Comment by micahtdew** [comment]
tysm ur great :D
